export const permissions = {
  view: 'view',
  church_view: 'church:view',
  church_edit: 'church:edit',
  church_add: 'church:add',
  driver_view: 'driver:view',
  driver_edit: 'driver:edit',
  driver_add: 'driver:add',
  passenger_view: 'passenger:view',
  passenger_edit: 'passenger:edit',
  passenger_add: 'passenger:add',
  ride_view: 'ride:view',
  ride_edit: 'ride:edit',
  ride_add: 'ride:add',
  bus_view: 'bus:view',
  bus_edit: 'bus:edit',
  bus_add: 'bus:add',
  event_view: 'event:view',
  event_edit: 'event:edit',
  event_add: 'event:add',
  advert_view: 'advert:view',
  advert_edit: 'advert:edit',
  advert_add: 'advert:add',
};

export const permissionRules = {
  gospoolAdmin: [
    permissions.view,
    permissions.church_view,
    permissions.church_edit,
    permissions.church_add,
    permissions.driver_view,
    permissions.driver_edit,
    permissions.driver_add,
    permissions.passenger_view,
    permissions.passenger_edit,
    permissions.passenger_add,
    permissions.ride_view,
    permissions.ride_edit,
    permissions.ride_add,
  ],
  churchAdmin: [
    permissions.view,
    permissions.church_view,
    permissions.church_edit,
    permissions.bus_view,
    permissions.bus_edit,
    permissions.bus_add,
    permissions.event_view,
    permissions.event_edit,
    permissions.event_add,
    permissions.advert_view,
    permissions.advert_edit,
    permissions.advert_add,
  ],
  branchAdmin: [permissions.view, permissions.church_view],
  hod: [permissions.view, permissions.church_view],
} as Record<string, string[]>;
